import images from "@/constants/images";

export const messagesList = [
  {
    id: 1,
    sender: "Lisa Roy",
    content: "Hi, are you availale tommorow?",
    timestamp: "10:35 AM",
    read: true,
    unread: 0,
    userImage: images.user1,
    active: true,
  },
  {
    id: 2,
    sender: "Jamie Taylor",
    content: "Nice One Will Do it tommorow",
    timestamp: "10:35 AM",
    read: false,
    unread: 3,
    userImage: images.user2,
    active: false,
  },
  {
    id: 3,
    sender: "Jamie Taylor",
    content: "That's great, I am looking forward to having a great start",
    timestamp: "10:35 AM",
    read: true,
    unread: 0,
    userImage: images.user3,
    active: false,
  },
  {
    id: 4,
    sender: "Amy Frost",
    content: "Will start working on the chat app tommorow",
    timestamp: "10:35 AM",
    read: true,
    unread: 0,
    userImage: images.user4,
    active: false,
  },
  {
    id: 5,
    sender: "Paul Wilson",
    content: "Seee you tommorow champ",
    timestamp: "10:35 AM",
    read: true,
    unread: 0,
    userImage: images.user5,
    active: false,
  },
  {
    id: 6,
    sender: "Ana Williams",
    content: "??",
    timestamp: "10:35 AM",
    read: false,
    unread: 1,
    userImage: images.user3,
    active: false,
  },
];
